version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mssql_server
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./dump:/var/opt/mssql/dump
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
